# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvtPXOFaunJ9UZWaG6tp1L-URlLymFX5
"""

# Fix numpy — must be <2.0 for compatibility
# Colab has numpy 2.0.2 which breaks timm and pycocotools

# Downgrade numpy FIRST before anything else
!pip install "numpy==1.26.4" -q

# Then restart runtime to flush the old numpy from memory
print("numpy downgraded. NOW RESTART RUNTIME:")
print("Runtime menu → Restart session → then run Cell 2 onwards")
print("Do NOT run this cell again after restart.")

# ============================================================
# CELL 2: Install all packages (run after runtime restart)
# ============================================================

# Verify numpy is the right version now
import numpy as np
print(f"numpy version: {np.__version__}")
assert np.__version__.startswith("1.26"), \
    "Wrong numpy! Re-run Cell 1 and restart runtime."

# Install packages one by one with explicit versions
!pip install "Pillow==10.4.0"       -q
!pip install "scipy==1.13.1"        -q
!pip install "timm==0.9.16"         -q
!pip install "shapely==2.0.6"       -q
!pip install "einops==0.8.0"        -q
!pip install "matplotlib==3.9.2"    -q

# pycocotools — use this specific pre-built binary
# (pycocotools-fix also fails to build, use the official one
#  with the right numpy pinned first)
!pip install "pycocotools==2.0.7"   -q

print("\nAll packages installed. Verifying...")

import numpy;       print(f"  numpy        {numpy.__version__}")
import PIL;         print(f"  Pillow       {PIL.__version__}")
import scipy;       print(f"  scipy        {scipy.__version__}")
import timm;        print(f"  timm         {timm.__version__}")
import shapely;     print(f"  shapely      {shapely.__version__}")
import pycocotools; print(f"  pycocotools  OK")
import einops;      print(f"  einops       {einops.__version__}")
import torch;       print(f"  torch        {torch.__version__}")
print(f"  CUDA         {torch.cuda.is_available()}")
print("\nAll imports successful.")

# ============================================================
# CELL 3: Clone Hi-SAM + patch for PyTorch 2.x + numpy 1.26
# ============================================================
import os, glob

if not os.path.exists('/content/Hi-SAM'):
    !git clone https://github.com/ymy-k/Hi-SAM.git /content/Hi-SAM

os.chdir('/content/Hi-SAM')

py_files = glob.glob('/content/Hi-SAM/**/*.py', recursive=True)
print(f"Scanning {len(py_files)} Python files...\n")

# ── Patch 1: autocast API ──────────────────────────────────
for fpath in py_files:
    with open(fpath, 'r', errors='ignore') as f:
        txt = f.read()
    if 'torch.cuda.amp.autocast' in txt:
        with open(fpath, 'w') as f:
            f.write(txt.replace('torch.cuda.amp.autocast',
                                'torch.amp.autocast'))
        print(f"  [autocast]   {os.path.basename(fpath)}")

# ── Patch 2: .type(torch.bool) ────────────────────────────
for fpath in py_files:
    with open(fpath, 'r', errors='ignore') as f:
        txt = f.read()
    if '.type(torch.bool)' in txt:
        with open(fpath, 'w') as f:
            f.write(txt.replace('.type(torch.bool)', '.bool()'))
        print(f"  [torch.bool] {os.path.basename(fpath)}")

# ── Patch 3: np.int / np.float (removed in numpy 1.24+) ───
for fpath in py_files:
    with open(fpath, 'r', errors='ignore') as f:
        txt = f.read()
    changed = False
    if 'np.int,' in txt or 'np.int)' in txt:
        txt     = txt.replace('np.int,',  'np.int64,')\
                     .replace('np.int)',  'np.int64)')
        changed = True
    if 'np.float,' in txt or 'np.float)' in txt:
        txt     = txt.replace('np.float,', 'np.float64,')\
                     .replace('np.float)', 'np.float64)')
        changed = True
    if changed:
        with open(fpath, 'w') as f:
            f.write(txt)
        print(f"  [np.int/float] {os.path.basename(fpath)}")

# ── Patch 4: strip torch pin from requirements.txt ────────
req = '/content/Hi-SAM/requirements.txt'
with open(req) as f:
    lines = f.readlines()
with open(req, 'w') as f:
    f.writelines([l for l in lines
                  if not l.lower().startswith('torch')])
print("\nrequirements.txt — torch lines removed")
print("All patches done.")

# ============================================================
# CELL 4: Download SAM ViT-H weights + upload Hi-SAM checkpoint
# ============================================================
import os
os.makedirs('/content/Hi-SAM/pretrained_checkpoint', exist_ok=True)

# ── SAM ViT-H base weights (~2.4 GB, auto download) ────────
vit_h_path = '/content/Hi-SAM/pretrained_checkpoint/sam_vit_h_4b8939.pth'
if not os.path.exists(vit_h_path):
    print("Downloading SAM ViT-H weights (~2.4 GB)...")
    !wget -q --show-progress \
        "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth" \
        -O {vit_h_path}
    print("Download complete.")
else:
    print("SAM ViT-H weights already present.")

# ── Upload line_detection_ctw1500.pth manually ─────────────
# Get this from the OneDrive link in Hi-SAM README:
# https://github.com/ymy-k/Hi-SAM  → Checkpoints section
# → line_detection_ctw1500.pth  (trained on CTW1500)
print("\nUpload line_detection_ctw1500.pth now:")
from google.colab import files
uploaded = files.upload()
for fname in uploaded:
    dest = f'/content/Hi-SAM/pretrained_checkpoint/{fname}'
    os.rename(fname, dest)
    print(f"  Saved: {dest}")

print("\nAll checkpoints:")
!ls -lh /content/Hi-SAM/pretrained_checkpoint/

# Upload Odia scene text image

import os, shutil
from google.colab import files

os.makedirs('/content/Hi-SAM/odia_input', exist_ok=True)

print("Upload your Odia scene text image:")
uploaded = files.upload()

for fname in uploaded:
    dest = f'/content/Hi-SAM/odia_input/{fname}'
    shutil.move(fname, dest)
    INPUT_IMAGE_PATH = dest
    print(f"Saved: {INPUT_IMAGE_PATH}")

# ============================================================
# CELL 6: FINAL — Label map approach
# Each pixel assigned to exactly ONE line → zero overlap
# zero blank lines → no subtraction needed
# ============================================================
import sys, os
sys.path.insert(0, '/content/Hi-SAM')
os.chdir('/content/Hi-SAM')

import numpy as np
import torch
from argparse import Namespace
from PIL import Image, ImageDraw
from shapely.geometry import MultiPolygon, MultiPoint
from shapely.validation import make_valid

from hi_sam.modeling.build import model_registry
from hi_sam.modeling.auto_mask_generator import AutoMaskGenerator

# ══════════════════════════════════════════════════════════
# CONFIG
# ══════════════════════════════════════════════════════════
CHECKPOINT        = 'pretrained_checkpoint/line_detection_ctw1500.pth'
MODEL_TYPE        = 'vit_h'
INPUT_IMAGE       = INPUT_IMAGE_PATH
OUTPUT_DIR        = '/content/Hi-SAM/odia_lines_output'
FG_POINTS_NUM     = 600
BATCH_POINTS_NUM  = 100
SCORE_THRESH      = 0.5
NMS_THRESH        = 0.5
MIN_AREA_FRACTION = 0.0008
POLYGON_TOLERANCE = 1.5
CROP_PADDING      = 6
# ══════════════════════════════════════════════════════════

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ─────────────────────────────────────────────────────────
# 1. Build model
# ─────────────────────────────────────────────────────────
args = Namespace(
    checkpoint  = CHECKPOINT,
    model_type  = MODEL_TYPE,
    hier_det    = True,
    attn_layers = 12,
    prompt_len  = 12,
)
print("Building Hi-SAM model...")
sam = model_registry[MODEL_TYPE](args)
sam.eval()
device = 'cuda' if torch.cuda.is_available() else 'cpu'
sam.to(device)
print(f"  Model on: {device}")

# ─────────────────────────────────────────────────────────
# 2. Load image
# ─────────────────────────────────────────────────────────
pil_image = Image.open(INPUT_IMAGE).convert('RGB')
W, H      = pil_image.size
img_array = np.array(pil_image)
img_area  = H * W
print(f"  Image: {W} × {H} px")

# ─────────────────────────────────────────────────────────
# 3. Run Hi-SAM
# ─────────────────────────────────────────────────────────
print("Running Hi-SAM line detection (1-3 min)...")
generator = AutoMaskGenerator(sam)
generator.set_image(img_array)

with torch.no_grad():
    masks_np, scores_np = generator.predict_text_detection(
        from_low_res     = False,
        fg_points_num    = FG_POINTS_NUM,
        batch_points_num = BATCH_POINTS_NUM,
        score_thresh     = SCORE_THRESH,
        nms_thresh       = NMS_THRESH,
        return_logits    = False,
        zero_shot        = True,
        dataset          = 'ctw1500',
    )

if masks_np is None:
    raise RuntimeError("No text detected. Try lowering score_thresh.")
print(f"  Raw masks: {masks_np.shape[0]}")

# ─────────────────────────────────────────────────────────
# 4. Filter small masks
# ─────────────────────────────────────────────────────────
masks_2d = []
for i in range(masks_np.shape[0]):
    m = masks_np[i, 0, :, :]
    if m.sum() >= img_area * MIN_AREA_FRACTION:
        masks_2d.append(m)

print(f"  After area filter: {len(masks_2d)} masks")

# ─────────────────────────────────────────────────────────
# 5. Deduplicate — pixel overlap only
#    Only merge masks that share actual pixels
#    (true duplicates = same line detected twice)
# ─────────────────────────────────────────────────────────
def pixel_overlap_ratio(m1, m2):
    inter    = np.logical_and(m1, m2).sum()
    if inter == 0:
        return 0.0
    min_area = min(m1.sum(), m2.sum())
    return inter / min_area if min_area > 0 else 0.0

print("Deduplicating...")
used, deduped = [False] * len(masks_2d), []

for i in range(len(masks_2d)):
    if used[i]:
        continue
    group = [masks_2d[i]]
    for j in range(i + 1, len(masks_2d)):
        if not used[j] and \
           pixel_overlap_ratio(masks_2d[i], masks_2d[j]) > 0.50:
            group.append(masks_2d[j])
            used[j] = True
    combined = group[0].copy()
    for mk in group[1:]:
        combined = combined | mk
    deduped.append(combined)
    used[i] = True

# Sort top → bottom
deduped.sort(key=lambda m: np.where(m)[0].mean())
print(f"  Before: {len(masks_2d)}  After: {len(deduped)}")

# ─────────────────────────────────────────────────────────
# 6. BUILD LABEL MAP
#    This is the key fix. Instead of polygon subtraction
#    (which destroys masks), we assign each pixel to
#    exactly one line using a label map.
#
#    Rules:
#    - Paint masks largest-first onto the label map
#    - Smaller masks paint on top (overwrite large masks)
#    - Each pixel ends up with exactly ONE label
#    - No polygon math needed — works purely on pixels
#    - Zero blank lines, zero overlaps guaranteed
# ─────────────────────────────────────────────────────────
print("Building label map...")

# label_map[y, x] = line index (1-based), 0 = background
label_map = np.zeros((H, W), dtype=np.int32)

# Sort largest → smallest so smaller masks paint on top
sorted_by_size = sorted(
    enumerate(deduped, start=1),
    key=lambda x: x[1].sum(),
    reverse=True   # largest first = painted first = overwritten by smaller
)

for label_idx, mask in sorted_by_size:
    label_map[mask] = label_idx

# ─────────────────────────────────────────────────────────
# 7. Extract final clean masks from label map
#    Each mask is now guaranteed non-overlapping
#    Re-sort top → bottom for L1, L2, L3 naming
# ─────────────────────────────────────────────────────────
print("Extracting clean masks from label map...")
clean = []

for label_idx, original_mask in enumerate(deduped, start=1):
    # Get the pixels exclusively assigned to this line
    clean_mask = (label_map == label_idx)
    pixel_count = clean_mask.sum()

    if pixel_count < 50:
        continue

    # Get vertical centroid for sorting
    rows = np.where(clean_mask)[0]
    v_center = rows.mean() if len(rows) > 0 else 0
    clean.append((clean_mask, v_center))

# Sort top → bottom
clean.sort(key=lambda x: x[1])
clean = [(mask, None) for mask, _ in clean]

print(f"  Final non-overlapping lines: {len(clean)}")

# ─────────────────────────────────────────────────────────
# 8. Convert clean masks → Shapely polygons for visualization
# ─────────────────────────────────────────────────────────
def mask_to_polygon(bool_mask, tolerance=1.5):
    rows, cols = np.where(bool_mask)
    if len(rows) == 0:
        return None
    padded = np.pad(bool_mask, 1, constant_values=False)
    all_nbrs = (
        padded[1:-1, 1:-1] &
        padded[0:-2, 1:-1] &
        padded[2:  , 1:-1] &
        padded[1:-1, 0:-2] &
        padded[1:-1, 2:  ]
    )
    boundary = bool_mask & ~all_nbrs
    br, bc   = np.where(boundary)
    if len(br) < 3:
        pts = list(zip(cols.tolist(), rows.tolist()))
        return make_valid(MultiPoint(pts).convex_hull) \
               if len(pts) >= 3 else None
    pts     = list(zip(bc.tolist(), br.tolist()))
    dilated = MultiPoint(pts).buffer(2.5, resolution=4)
    poly    = make_valid(dilated)
    if isinstance(poly, MultiPolygon):
        poly = max(poly.geoms, key=lambda p: p.area)
    poly = poly.simplify(tolerance, preserve_topology=True)
    return make_valid(poly) if not poly.is_empty else None

print("Building polygons for visualization...")
clean_with_poly = []
for mask, _ in clean:
    poly = mask_to_polygon(mask, POLYGON_TOLERANCE)
    clean_with_poly.append((poly, mask))

# Replace clean with version that includes polygons
clean = clean_with_poly
print(f"Done. {len(clean)} lines ready.")
print("Run Cell 6b to preview, then Cell 7 to save.")

# ─────────────────────────────────────────────────────────
# Helper used by Cell 6b and Cell 7
# ─────────────────────────────────────────────────────────
def to_pil_coords(poly):
    if isinstance(poly, MultiPolygon):
        poly = max(poly.geoms, key=lambda p: p.area)
    return [(float(x), float(y)) for x, y in poly.exterior.coords]

# ============================================================
# CELL 6b: PREVIEW — show detected lines before saving
# Run this AFTER Cell 6 segmentation, BEFORE saving
# Shows polygon outlines + line numbers on original image
# Tells you total lines detected so you can adjust if needed
# ============================================================
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from PIL import Image, ImageDraw
import numpy as np

# ── Draw polygon outlines on a copy of original image ──────
preview     = pil_image.copy()
draw        = ImageDraw.Draw(preview)

# High-contrast color palette for line boundaries
palette = [
    '#00FF00',  # bright green
    '#FF4444',  # red
    '#4488FF',  # blue
    '#FFD700',  # gold
    '#FF69B4',  # pink
    '#00FFFF',  # cyan
    '#FF8C00',  # orange
    '#ADFF2F',  # yellow-green
    '#FF00FF',  # magenta
    '#00CED1',  # dark turquoise
    '#FF6347',  # tomato
    '#7FFFD4',  # aquamarine
]

print(f"Total lines detected: {len(clean)}")
print("─" * 40)

for idx, (poly, _) in enumerate(clean, start=1):
    coords = to_pil_coords(poly)
    color  = palette[(idx - 1) % len(palette)]

    # Draw polygon outline (draw 3 times for thickness)
    draw.polygon(coords, outline=color)
    draw.polygon(coords, outline=color)
    draw.polygon(coords, outline=color)

    # Label at centroid
    cx = int(poly.centroid.x)
    cy = int(poly.centroid.y)

    # Small filled circle at centroid for visibility
    r = 6
    draw.ellipse([cx-r, cy-r, cx+r, cy+r], fill=color)

    # Line number text
    draw.text((cx + 8, cy - 8), f'L{idx}', fill=color)

    # Print line info
    xs = [c[0] for c in coords]
    ys = [c[1] for c in coords]
    w  = int(max(xs) - min(xs))
    h  = int(max(ys) - min(ys))
    print(f"  L{idx:02d} | bbox: {w}×{h}px "
          f"| centroid: ({cx},{cy}) "
          f"| vertices: {len(coords)}")

print("─" * 40)
print(f"Total: {len(clean)} lines detected")
print("\nIf count looks wrong, adjust these in Cell 6 CONFIG:")
print("  POINTS_PER_SIDE    (current: 32)  → raise to 48 for more lines")
print("  MIN_AREA_FRACTION  (current: 0.0008) → lower to catch small lines")
print("  OVERLAP_IOU_THRESH (current: 0.30) → lower to split merged lines")

# ── Display the preview image ───────────────────────────────
fig, ax = plt.subplots(1, 1, figsize=(12, 16))
ax.imshow(preview)
ax.set_title(
    f"Hi-SAM Line Detection Preview\n"
    f"{len(clean)} lines detected  |  "
    f"Image: {W}×{H}px\n"
    f"Green outlines = detected text lines",
    fontsize=13, pad=12
)
ax.axis('off')

# ── Add legend on the side ──────────────────────────────────
legend_patches = [
    mpatches.Patch(color=palette[(i) % len(palette)],
                   label=f'L{i+1}')
    for i in range(len(clean))
]
ax.legend(
    handles     = legend_patches,
    loc         = 'upper right',
    bbox_to_anchor = (1.18, 1.0),
    fontsize    = 9,
    title       = "Lines",
    title_fontsize = 10,
    framealpha  = 0.8
)

plt.tight_layout()
plt.show()

# ── Also show a zoomed strip showing first 5 lines ─────────
if len(clean) > 0:
    print("\nZoomed preview of first 5 lines:")
    fig2, axes = plt.subplots(
        min(5, len(clean)), 1,
        figsize=(10, min(5, len(clean)) * 1.8)
    )
    if len(clean) == 1:
        axes = [axes]

    for i, (poly, _) in enumerate(clean[:5]):
        coords = to_pil_coords(poly)
        xs = [c[0] for c in coords]
        ys = [c[1] for c in coords]
        x1 = max(0, int(min(xs)) - 10)
        y1 = max(0, int(min(ys)) - 10)
        x2 = min(W, int(max(xs)) + 10)
        y2 = min(H, int(max(ys)) + 10)

        # Crop from ORIGINAL image (no polygon drawing)
        strip = pil_image.crop((x1, y1, x2, y2))
        axes[i].imshow(strip)
        axes[i].set_title(
            f'L{i+1}  |  {x2-x1}×{y2-y1}px',
            fontsize=10, loc='left'
        )
        axes[i].axis('off')

    plt.suptitle("First 5 line crops preview "
                 "(original image, no mask applied)",
                 fontsize=11)
    plt.tight_layout()
    plt.show()

# ============================================================
# CELL 7: Save each line as PNG using clean label map masks
# Uses the pixel mask directly — polygon only for vis
# ============================================================
import os
import numpy as np
from PIL import Image, ImageDraw

OUTPUT_DIR   = '/content/Hi-SAM/odia_lines_output'
CROP_PADDING = 6

os.makedirs(OUTPUT_DIR, exist_ok=True)
print(f"Saving {len(clean)} lines → {OUTPUT_DIR}")
print("─" * 50)

saved   = []
skipped = []

for idx, (poly, mask) in enumerate(clean, start=1):
    try:
        # mask is already a clean non-overlapping bool H×W array
        if mask is None or mask.sum() < 50:
            skipped.append(idx)
            print(f"  L{idx:02d}: SKIP — empty mask")
            continue

        mask_arr = (mask.astype(np.uint8)) * 255

        # Bounding box
        ys_m, xs_m = np.where(mask_arr > 0)
        x1 = max(0, int(xs_m.min()) - CROP_PADDING)
        y1 = max(0, int(ys_m.min()) - CROP_PADDING)
        x2 = min(W, int(xs_m.max()) + CROP_PADDING)
        y2 = min(H, int(ys_m.max()) + CROP_PADDING)

        if x2 <= x1 or y2 <= y1:
            skipped.append(idx)
            continue

        # Composite
        mask_img   = Image.fromarray(mask_arr, mode='L')
        white_bg   = Image.new('RGB', (W, H), (255, 255, 255))
        composited = Image.composite(pil_image, white_bg,
                                     mask_img)

        # Crop
        line_crop  = composited.crop((x1, y1, x2, y2))

        # Save
        out_path = os.path.join(OUTPUT_DIR, f'L{idx}.png')
        line_crop.save(out_path)
        saved.append(out_path)
        print(f"  L{idx:02d}.png  |  "
              f"{x2-x1}×{y2-y1}px  |  "
              f"{int(mask.sum())} pixels")

    except Exception as e:
        print(f"  L{idx:02d}: ERROR — {e}")
        skipped.append(idx)

print("─" * 50)
print(f"Saved  : {len(saved)}")
if skipped:
    print(f"Skipped: {skipped}")

# ============================================================
# CELL 7: Save each line as PNG with blank detection + fallback
# Blank lines are either:
#   1. Mask lost all pixels during overlap subtraction
#   2. Polygon too small after simplification
#   3. Original Hi-SAM mask was a false positive
# Fix: use original Hi-SAM mask directly as fallback
# ============================================================
import os
import numpy as np
from PIL import Image, ImageDraw

OUTPUT_DIR   = '/content/Hi-SAM/odia_lines_output'
CROP_PADDING = 6
MIN_PIXELS   = 100   # minimum pixels to consider a valid line

os.makedirs(OUTPUT_DIR, exist_ok=True)

print(f"Saving {len(clean)} lines to {OUTPUT_DIR}")
print("─" * 55)

saved   = []
skipped = []

for idx, (poly, original_mask) in enumerate(clean, start=1):
    try:
        coords = to_pil_coords(poly)

        # ── Check 1: polygon has enough vertices ───────────
        if len(coords) < 3:
            skipped.append(idx)
            print(f"  L{idx:02d}: SKIP — too few polygon vertices")
            continue

        # ── Check 2: polygon area is large enough ──────────
        xs = [c[0] for c in coords]
        ys = [c[1] for c in coords]
        poly_w = int(max(xs)) - int(min(xs))
        poly_h = int(max(ys)) - int(min(ys))

        if poly_w < 5 or poly_h < 3:
            skipped.append(idx)
            print(f"  L{idx:02d}: SKIP — polygon too small "
                  f"({poly_w}×{poly_h}px)")
            continue

        # ── Draw polygon mask on full canvas ───────────────
        mask_canvas = Image.new('L', (W, H), 0)
        ImageDraw.Draw(mask_canvas).polygon(coords, fill=255)
        mask_arr = np.array(mask_canvas)

        # ── Check 3: mask has actual pixels ────────────────
        pixel_count = (mask_arr > 0).sum()

        if pixel_count < MIN_PIXELS:
            # FALLBACK: use the original Hi-SAM boolean mask
            # instead of the Shapely-processed polygon
            print(f"  L{idx:02d}: polygon empty ({pixel_count}px), "
                  f"using original Hi-SAM mask as fallback")

            if original_mask is not None and \
               isinstance(original_mask, np.ndarray):
                # original_mask is bool H×W from Hi-SAM
                fallback = (original_mask.astype(np.uint8)) * 255
                mask_canvas = Image.fromarray(fallback, mode='L')
                mask_arr    = fallback
                pixel_count = (mask_arr > 0).sum()

                if pixel_count < MIN_PIXELS:
                    skipped.append(idx)
                    print(f"         fallback also empty, skipping")
                    continue
            else:
                skipped.append(idx)
                print(f"         no fallback available, skipping")
                continue

        # ── Bounding box from actual mask pixels ───────────
        # Use mask_arr directly for tight bbox
        # (more reliable than polygon coords after fallback)
        ys_mask, xs_mask = np.where(mask_arr > 0)
        x1 = max(0, int(xs_mask.min()) - CROP_PADDING)
        y1 = max(0, int(ys_mask.min()) - CROP_PADDING)
        x2 = min(W, int(xs_mask.max()) + CROP_PADDING)
        y2 = min(H, int(ys_mask.max()) + CROP_PADDING)

        if x2 <= x1 or y2 <= y1:
            skipped.append(idx)
            print(f"  L{idx:02d}: SKIP — invalid bounding box")
            continue

        # ── Composite: original inside mask, white outside ─
        white_bg   = Image.new('RGB', (W, H), (255, 255, 255))
        composited = Image.composite(
            pil_image, white_bg,
            Image.fromarray(mask_arr, mode='L')
        )

        # ── Crop to bounding box ───────────────────────────
        line_crop = composited.crop((x1, y1, x2, y2))

        # ── Final blank check on the crop itself ───────────
        crop_arr = np.array(line_crop)
        # A blank image has all pixels = 255 (white)
        is_blank = (crop_arr == 255).all()
        if is_blank:
            skipped.append(idx)
            print(f"  L{idx:02d}: SKIP — crop is fully white")
            continue

        # ── Save ───────────────────────────────────────────
        out_path = os.path.join(OUTPUT_DIR, f'L{idx}.png')
        line_crop.save(out_path)
        saved.append(out_path)

        print(f"  L{idx:02d}.png  |  {x2-x1}×{y2-y1}px  "
              f"|  {pixel_count} mask pixels  "
              f"|  {len(coords)} poly vertices")

    except Exception as e:
        print(f"  L{idx:02d}: ERROR — {e}")
        skipped.append(idx)

print("─" * 55)
print(f"Saved  : {len(saved)} lines")
if skipped:
    print(f"Skipped: {len(skipped)} lines → {skipped}")
    print("  (skipped lines had empty masks after overlap removal)")

# ============================================================
# CELL 8: Verify all saved PNGs + display grid
# ============================================================
import glob
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np

line_files = sorted(
    glob.glob(os.path.join(OUTPUT_DIR, 'L*.png')),
    key=lambda p: int(
        os.path.splitext(os.path.basename(p))[0][1:])
)

print(f"PNG files in {OUTPUT_DIR}:")
for f in line_files:
    size = os.path.getsize(f)
    print(f"  {os.path.basename(f)}  —  {size/1024:.1f} KB")

print(f"\nTotal: {len(line_files)} files")

# ── Display grid ───────────────────────────────────────────
if line_files:
    cols      = 3
    rows      = (len(line_files) + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols,
                             figsize=(15, rows * 2.5))
    axes_flat = list(np.array(axes).flatten()) \
                if rows > 1 else list(axes) \
                if cols > 1 else [axes]

    for i, fpath in enumerate(line_files):
        img = mpimg.imread(fpath)
        axes_flat[i].imshow(img)
        axes_flat[i].set_title(
            os.path.basename(fpath), fontsize=9)
        axes_flat[i].axis('off')
    for j in range(i + 1, len(axes_flat)):
        axes_flat[j].axis('off')

    plt.suptitle(
        f"All {len(line_files)} saved line crops",
        fontsize=12)
    plt.tight_layout()
    plt.show()

# ============================================================
# CELL 10: Word segmentation using word_detection_totaltext.pth
# Runs Hi-SAM word detection model on each line crop
# Saves: L1W1.png, L1W2.png, L2W1.png ...
# ============================================================
import os, glob, sys
import numpy as np
import torch
from PIL import Image
from argparse import Namespace

sys.path.insert(0, '/content/Hi-SAM')
os.chdir('/content/Hi-SAM')

from hi_sam.modeling.build import model_registry
from hi_sam.modeling.auto_mask_generator import AutoMaskGenerator

# ══════════════════════════════════════════════════════════
# CONFIG
# ══════════════════════════════════════════════════════════
WORD_CHECKPOINT   = 'pretrained_checkpoint/word_detection_totaltext.pth'
WORD_MODEL_TYPE   = 'vit_h'
LINE_INPUT_DIR    = '/content/Hi-SAM/odia_lines_output'
WORD_OUTPUT_DIR   = '/content/Hi-SAM/odia_words_output'
WORD_FG_POINTS    = 300
WORD_BATCH_POINTS = 50
WORD_SCORE_THRESH = 0.3
WORD_NMS_THRESH   = 0.3
WORD_MIN_AREA     = 0.002   # min 0.2% of line image area
WORD_CROP_PADDING = 3
# ══════════════════════════════════════════════════════════

os.makedirs(WORD_OUTPUT_DIR, exist_ok=True)

# ─────────────────────────────────────────────────────────
# 1. Detect attn_layers from word checkpoint
# ─────────────────────────────────────────────────────────
print("Reading word checkpoint...")
ckpt  = torch.load(WORD_CHECKPOINT, map_location='cpu')
state = ckpt['model'] if isinstance(ckpt, dict) \
        and 'model' in ckpt else ckpt

attn_layers = 1
for k, v in state.items():
    if 'modal_aligner.conv.0.weight' in k:
        attn_layers = v.shape[0]
        print(f"  Detected attn_layers={attn_layers} "
              f"from {k} shape {v.shape}")
        break

# Check if checkpoint has hi_decoder
has_hi_decoder = any('hi_decoder' in k for k in state.keys())
print(f"  Has hi_decoder: {has_hi_decoder}")
del ckpt, state

# ─────────────────────────────────────────────────────────
# 2. Build word detection model
# ─────────────────────────────────────────────────────────
print("\nBuilding word detection model...")
word_args = Namespace(
    checkpoint  = WORD_CHECKPOINT,
    model_type  = WORD_MODEL_TYPE,
    hier_det    = has_hi_decoder,
    attn_layers = attn_layers,
    prompt_len  = attn_layers,
)
word_sam = model_registry[WORD_MODEL_TYPE](word_args)
word_sam.eval()
device = 'cuda' if torch.cuda.is_available() else 'cpu'
word_sam.to(device)
print(f"  Word model on: {device}")

# ─────────────────────────────────────────────────────────
# 3. Helpers
# ─────────────────────────────────────────────────────────
def pixel_overlap_ratio(m1, m2):
    inter    = np.logical_and(m1, m2).sum()
    if inter == 0:
        return 0.0
    min_area = min(m1.sum(), m2.sum())
    return inter / min_area if min_area > 0 else 0.0

def deduplicate_masks(masks_list, thresh=0.50):
    used, result = [False] * len(masks_list), []
    for i in range(len(masks_list)):
        if used[i]:
            continue
        group = [masks_list[i]]
        for j in range(i + 1, len(masks_list)):
            if not used[j] and \
               pixel_overlap_ratio(masks_list[i],
                                   masks_list[j]) > thresh:
                group.append(masks_list[j])
                used[j] = True
        combined = group[0].copy()
        for mk in group[1:]:
            combined = combined | mk
        result.append(combined)
        used[i] = True
    return result

def build_label_map(masks_list, H, W):
    label_map    = np.zeros((H, W), dtype=np.int32)
    sorted_masks = sorted(
        enumerate(masks_list, start=1),
        key=lambda x: x[1].sum(),
        reverse=True
    )
    for label_idx, mask in sorted_masks:
        label_map[mask] = label_idx
    return label_map

# ─────────────────────────────────────────────────────────
# 4. Get line files
# ─────────────────────────────────────────────────────────
line_files = sorted(
    glob.glob(os.path.join(LINE_INPUT_DIR, 'L*.png')),
    key=lambda p: int(
        os.path.splitext(os.path.basename(p))[0][1:])
)
print(f"\nFound {len(line_files)} line crops")
print(f"Saving words to: {WORD_OUTPUT_DIR}\n")

# ─────────────────────────────────────────────────────────
# 5. Process each line crop
# ─────────────────────────────────────────────────────────
total_words_saved = 0
line_summary      = []

for line_path in line_files:
    line_name = os.path.splitext(
                    os.path.basename(line_path))[0]

    print(f"── {line_name} ", end='', flush=True)

    # Load line crop
    line_pil   = Image.open(line_path).convert('RGB')
    lW, lH     = line_pil.size
    line_array = np.array(line_pil)
    line_area  = lW * lH

    if lW < 20 or lH < 8:
        print(f"too small ({lW}×{lH}), skip")
        line_summary.append((line_name, 0))
        continue

    # ── Run word detection on this line crop ───────────────
    try:
        word_gen = AutoMaskGenerator(word_sam)
        word_gen.set_image(line_array)

        with torch.no_grad():
            wmasks_np, wscores = \
                word_gen.predict_text_detection(
                    from_low_res     = False,
                    fg_points_num    = WORD_FG_POINTS,
                    batch_points_num = WORD_BATCH_POINTS,
                    score_thresh     = WORD_SCORE_THRESH,
                    nms_thresh       = WORD_NMS_THRESH,
                    return_logits    = False,
                    zero_shot        = False,
                    dataset          = 'totaltext',
                )

    except Exception as e:
        print(f"error: {e}")
        line_summary.append((line_name, 0))
        continue

    if wmasks_np is None:
        print("no words detected")
        line_summary.append((line_name, 0))
        continue

    print(f"raw={wmasks_np.shape[0]} ", end='', flush=True)

    # ── Filter by minimum area ─────────────────────────────
    words_2d = []
    for i in range(wmasks_np.shape[0]):
        m = wmasks_np[i, 0, :, :]
        if m.sum() >= line_area * WORD_MIN_AREA:
            words_2d.append(m)

    if not words_2d:
        print("all masks too small")
        line_summary.append((line_name, 0))
        continue

    # ── Deduplicate + label map ────────────────────────────
    words_deduped = deduplicate_masks(words_2d)
    label_map     = build_label_map(words_deduped, lH, lW)

    # ── Collect word masks sorted left → right ─────────────
    word_clean = []
    for label_idx in range(1, len(words_deduped) + 1):
        clean_mask = (label_map == label_idx)
        if clean_mask.sum() < 30:
            continue
        cols     = np.where(clean_mask)[1]
        h_center = cols.mean() if len(cols) > 0 else 0
        word_clean.append((clean_mask, h_center))

    word_clean.sort(key=lambda x: x[1])

    # ── Save each word crop ────────────────────────────────
    words_saved = 0
    white_bg    = Image.new('RGB', (lW, lH), (255, 255, 255))

    for word_num, (word_mask, _) in \
            enumerate(word_clean, start=1):

        mask_arr = (word_mask.astype(np.uint8)) * 255

        ys_w, xs_w = np.where(mask_arr > 0)
        x1 = max(0,  int(xs_w.min()) - WORD_CROP_PADDING)
        y1 = max(0,  int(ys_w.min()) - WORD_CROP_PADDING)
        x2 = min(lW, int(xs_w.max()) + WORD_CROP_PADDING)
        y2 = min(lH, int(ys_w.max()) + WORD_CROP_PADDING)

        if x2 <= x1 or y2 <= y1:
            continue

        mask_img   = Image.fromarray(mask_arr)
        composited = Image.composite(
            line_pil, white_bg, mask_img)
        word_crop  = composited.crop((x1, y1, x2, y2))

        if (np.array(word_crop) == 255).all():
            continue

        # Save as PNG (avoids Pillow JPEG bug)
        out_path = os.path.join(
            WORD_OUTPUT_DIR,
            f'{line_name}W{word_num}.png')
        word_crop.save(out_path)

        words_saved       += 1
        total_words_saved += 1

    print(f"→ {words_saved} words")
    line_summary.append((line_name, words_saved))

# ─────────────────────────────────────────────────────────
# 6. Summary
# ─────────────────────────────────────────────────────────
print("\n" + "═" * 45)
print(f"  TOTAL WORD IMAGES SAVED: {total_words_saved}")
print("═" * 45)
print(f"\n  {'Line':<8} {'Words':>5}  {'Visual'}")
print("  " + "─" * 38)
for lname, count in line_summary:
    bar = '█' * min(count, 28)
    print(f"  {lname:<8} {count:>5}  {bar}")
print("  " + "─" * 38)
print(f"  {'TOTAL':<8} {total_words_saved:>5}")



# ============================================================
# CELL 11: Preview word crops grouped by line
# ============================================================
import glob
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import os
from collections import defaultdict

WORD_OUTPUT_DIR = '/content/Hi-SAM/odia_words_output'

word_files = sorted(
    glob.glob(os.path.join(WORD_OUTPUT_DIR, 'L*.png')),
    key=lambda p: (
        int(os.path.basename(p).split('W')[0][1:]),
        int(os.path.splitext(
            os.path.basename(p).split('W')[1])[0])
    )
)
print(f"Total word images: {len(word_files)}")

by_line = defaultdict(list)
for f in word_files:
    lk = os.path.basename(f).split('W')[0]
    by_line[lk].append(f)

line_keys = sorted(by_line.keys(),
                   key=lambda k: int(k[1:]))

for lk in line_keys:
    words = by_line[lk]
    if not words:
        continue
    n    = len(words)
    fig, axes = plt.subplots(
        1, n, figsize=(max(6, n * 1.6), 2.2))
    if n == 1:
        axes = [axes]
    for i, wp in enumerate(words):
        img = mpimg.imread(wp)
        axes[i].imshow(img)
        axes[i].set_title(
            os.path.splitext(
                os.path.basename(wp))[0],
            fontsize=7)
        axes[i].axis('off')
    plt.suptitle(f"{lk} — {n} words",
                 fontsize=10, y=1.02)
    plt.tight_layout()
    plt.show()

!zip -r /content/Hi-SAM.zip /content/Hi-SAM

from google.colab import files
files.download('/content/Hi-SAM.zip')

# ============================================================
# CELL: Clear all GPU memory before starting
# Run this BEFORE the master cell
# ============================================================
import os

# Set PyTorch memory allocator to reduce fragmentation
os.environ['PYTORCH_ALLOC_CONF'] = 'expandable_segments:True'

import gc
import torch

# Kill any existing models in memory
for obj_name in list(globals().keys()):
    obj = globals()[obj_name]
    if hasattr(obj, 'parameters'):  # is a PyTorch model
        try:
            obj.cpu()
            del globals()[obj_name]
        except Exception:
            pass

gc.collect()
torch.cuda.empty_cache()
torch.cuda.synchronize()

print(f"GPU memory allocated : "
      f"{torch.cuda.memory_allocated()/1024**3:.2f} GB")
print(f"GPU memory reserved  : "
      f"{torch.cuda.memory_reserved()/1024**3:.2f} GB")
print(f"GPU memory free      : "
      f"{(torch.cuda.get_device_properties(0).total_memory - torch.cuda.memory_allocated())/1024**3:.2f} GB")

!rm -rf /content/Hi-SAM/odiascewimages_output/ADIPURUSHA_0001-079_output

# ============================================================
# MASTER CELL: All images — full memory management
# ============================================================
import os, glob, sys
import numpy as np
import torch
import gc
from PIL import Image
from argparse import Namespace
from shapely.geometry import MultiPolygon, MultiPoint
from shapely.validation import make_valid

# Must set BEFORE importing torch (or restart already did it)
os.environ['PYTORCH_ALLOC_CONF'] = 'expandable_segments:True'

sys.path.insert(0, '/content/Hi-SAM')
os.chdir('/content/Hi-SAM')

from hi_sam.modeling.build import model_registry
from hi_sam.modeling.auto_mask_generator import AutoMaskGenerator

# ══════════════════════════════════════════════════════════
# CONFIG
# ══════════════════════════════════════════════════════════
INPUT_FOLDER      = '/content/Hi-SAM/odiascewimages'
OUTPUT_ROOT       = '/content/Hi-SAM/odiascewimages_output'
LINE_CHECKPOINT   = 'pretrained_checkpoint/line_detection_ctw1500.pth'
WORD_CHECKPOINT   = 'pretrained_checkpoint/word_detection_totaltext.pth'
MODEL_TYPE        = 'vit_h'
MAX_IMAGE_SIZE    = 900    # aggressive resize to save memory

LINE_FG_POINTS    = 300
LINE_BATCH_POINTS = 30
LINE_SCORE_THRESH = 0.5
LINE_NMS_THRESH   = 0.5
LINE_MIN_AREA     = 0.0008
LINE_CROP_PAD     = 6

WORD_FG_POINTS    = 150
WORD_BATCH_POINTS = 20
WORD_SCORE_THRESH = 0.3
WORD_NMS_THRESH   = 0.3
WORD_MIN_AREA     = 0.002
WORD_CROP_PAD     = 3
# ══════════════════════════════════════════════════════════

os.makedirs(OUTPUT_ROOT, exist_ok=True)

# ─────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────
def free_gpu():
    gc.collect()
    torch.cuda.empty_cache()

def gpu_free_gb():
    props = torch.cuda.get_device_properties(0)
    free  = props.total_memory - torch.cuda.memory_allocated()
    return free / 1024**3

def load_model_cpu_first(checkpoint, model_type):
    """
    Load model weights on CPU first, then move to GPU.
    Detects args automatically from checkpoint.
    """
    ckpt  = torch.load(checkpoint, map_location='cpu')
    state = ckpt['model'] if isinstance(ckpt, dict) \
            and 'model' in ckpt else ckpt
    attn  = 1
    for k, v in state.items():
        if 'modal_aligner.conv.0.weight' in k:
            attn = v.shape[0]
            break
    has_hi = any('hi_decoder' in k for k in state.keys())
    del ckpt, state
    free_gpu()

    args = Namespace(
        checkpoint  = checkpoint,
        model_type  = model_type,
        hier_det    = has_hi,
        attn_layers = attn,
        prompt_len  = attn,
    )
    # Build on CPU first
    model = model_registry[model_type](args)
    model.eval()
    # Move to GPU
    model = model.cuda()
    return model

def unload(model):
    model.cpu()
    del model
    free_gpu()

def resize_img(pil_img, max_size):
    W, H  = pil_img.size
    if max(W, H) <= max_size:
        return pil_img
    scale = max_size / max(W, H)
    return pil_img.resize(
        (int(W * scale), int(H * scale)),
        Image.LANCZOS)

def pixel_overlap_ratio(m1, m2):
    inter    = np.logical_and(m1, m2).sum()
    if inter == 0:
        return 0.0
    min_area = min(m1.sum(), m2.sum())
    return inter / min_area if min_area > 0 else 0.0

def deduplicate_masks(masks_list, thresh=0.50):
    used, result = [False] * len(masks_list), []
    for i in range(len(masks_list)):
        if used[i]:
            continue
        group = [masks_list[i]]
        for j in range(i + 1, len(masks_list)):
            if not used[j] and \
               pixel_overlap_ratio(
                   masks_list[i], masks_list[j]) > thresh:
                group.append(masks_list[j])
                used[j] = True
        combined = group[0].copy()
        for mk in group[1:]:
            combined = combined | mk
        result.append(combined)
        used[i] = True
    return result

def build_label_map(masks_list, H, W):
    label_map = np.zeros((H, W), dtype=np.int32)
    for label_idx, mask in sorted(
            enumerate(masks_list, start=1),
            key=lambda x: x[1].sum(), reverse=True):
        label_map[mask] = label_idx
    return label_map

def save_crop(pil_img, mask_arr, out_path, W, H, pad):
    ys, xs = np.where(mask_arr > 0)
    if len(xs) == 0:
        return False
    x1 = max(0, int(xs.min()) - pad)
    y1 = max(0, int(ys.min()) - pad)
    x2 = min(W, int(xs.max()) + pad)
    y2 = min(H, int(ys.max()) + pad)
    if x2 <= x1 or y2 <= y1:
        return False
    white      = Image.new('RGB', (W, H), (255, 255, 255))
    mask_img   = Image.fromarray(mask_arr)
    composited = Image.composite(pil_img, white, mask_img)
    crop       = composited.crop((x1, y1, x2, y2))
    if (np.array(crop) == 255).all():
        return False
    crop.save(out_path)
    return True

# ─────────────────────────────────────────────────────────
# GET INPUT IMAGES
# ─────────────────────────────────────────────────────────
exts        = ('*.jpg','*.jpeg','*.png',
               '*.JPG','*.JPEG','*.PNG')
image_files = []
for ext in exts:
    image_files.extend(
        glob.glob(os.path.join(INPUT_FOLDER, ext)))
image_files = sorted(image_files)

print(f"Found {len(image_files)} images")
print(f"GPU free at start: {gpu_free_gb():.2f} GB\n")

# ─────────────────────────────────────────────────────────
# PROCESS EACH IMAGE
# ─────────────────────────────────────────────────────────
grand_summary = []

for img_idx, img_path in enumerate(image_files, start=1):

    img_name     = os.path.splitext(
                       os.path.basename(img_path))[0]
    img_out      = os.path.join(
                       OUTPUT_ROOT, f'{img_name}_output')
    line_dir     = os.path.join(img_out, 'Line')
    word_dir     = os.path.join(img_out, 'Word')
    os.makedirs(line_dir, exist_ok=True)
    os.makedirs(word_dir, exist_ok=True)

    print(f"╔{'═'*53}")
    print(f"║ [{img_idx}/{len(image_files)}] {img_name}")
    print(f"╚{'═'*53}")

    # Load + resize
    pil_orig  = Image.open(img_path).convert('RGB')
    pil_image = resize_img(pil_orig, MAX_IMAGE_SIZE)
    W, H      = pil_image.size
    img_array = np.array(pil_image)
    img_area  = H * W
    print(f"  {pil_orig.size[0]}×{pil_orig.size[1]}"
          f" → {W}×{H}  |  "
          f"GPU free: {gpu_free_gb():.2f} GB")
    del pil_orig

    # ══════════════════════════════════════════════════════
    # PHASE 1: LINE DETECTION
    # ══════════════════════════════════════════════════════
    print("  [Line] loading...", end='', flush=True)
    try:
        line_sam = load_model_cpu_first(
            LINE_CHECKPOINT, MODEL_TYPE)
    except torch.cuda.OutOfMemoryError:
        print(" OOM loading line model — "
              "restart runtime and try again")
        break
    print(f" ready  free={gpu_free_gb():.2f}GB")

    print("  [Line] detecting...", end='', flush=True)
    try:
        gen = AutoMaskGenerator(line_sam)
        gen.set_image(img_array)
        with torch.no_grad():
            masks_np, _ = gen.predict_text_detection(
                fg_points_num    = LINE_FG_POINTS,
                batch_points_num = LINE_BATCH_POINTS,
                score_thresh     = LINE_SCORE_THRESH,
                nms_thresh       = LINE_NMS_THRESH,
                zero_shot        = True,
                dataset          = 'ctw1500',
            )
        del gen
    except torch.cuda.OutOfMemoryError:
        print(" OOM — skipping image")
        unload(line_sam)
        grand_summary.append((img_name, 0, 0))
        continue

    unload(line_sam)
    print(f" done  free={gpu_free_gb():.2f}GB")

    if masks_np is None:
        print("  No lines found")
        grand_summary.append((img_name, 0, 0))
        continue

    # Process line masks on CPU
    masks_2d = [masks_np[i, 0, :, :]
                for i in range(masks_np.shape[0])
                if masks_np[i, 0, :, :].sum()
                   >= img_area * LINE_MIN_AREA]
    masks_2d.sort(key=lambda m: np.where(m)[0].mean())
    deduped   = deduplicate_masks(masks_2d)
    label_map = build_label_map(deduped, H, W)

    line_masks = []
    for lbl in range(1, len(deduped) + 1):
        cm = (label_map == lbl)
        if cm.sum() < 50:
            continue
        line_masks.append((cm, np.where(cm)[0].mean()))
    line_masks.sort(key=lambda x: x[1])

    # Save line crops
    saved_lines = []
    for l_idx, (lm, _) in enumerate(line_masks, start=1):
        marr = (lm.astype(np.uint8)) * 255
        lpath = os.path.join(line_dir, f'L{l_idx}.png')
        if save_crop(pil_image, marr, lpath,
                     W, H, LINE_CROP_PAD):
            saved_lines.append(
                (Image.open(lpath).convert('RGB'),
                 f'L{l_idx}'))

    n_lines = len(saved_lines)
    print(f"  Lines saved: {n_lines}")

    if n_lines == 0:
        grand_summary.append((img_name, 0, 0))
        continue

    # ══════════════════════════════════════════════════════
    # PHASE 2: WORD DETECTION
    # ══════════════════════════════════════════════════════
    print("  [Word] loading...", end='', flush=True)
    try:
        word_sam = load_model_cpu_first(
            WORD_CHECKPOINT, MODEL_TYPE)
    except torch.cuda.OutOfMemoryError:
        print(" OOM loading word model")
        grand_summary.append((img_name, n_lines, 0))
        continue
    print(f" ready  free={gpu_free_gb():.2f}GB")

    total_words = 0

    for line_pil, line_name in saved_lines:
        lW, lH    = line_pil.size
        line_arr  = np.array(line_pil)
        line_area = lW * lH

        if lW < 20 or lH < 8:
            continue

        print(f"    {line_name} ", end='', flush=True)

        try:
            wgen = AutoMaskGenerator(word_sam)
            wgen.set_image(line_arr)
            with torch.no_grad():
                wm_np, _ = wgen.predict_text_detection(
                    fg_points_num    = WORD_FG_POINTS,
                    batch_points_num = WORD_BATCH_POINTS,
                    score_thresh     = WORD_SCORE_THRESH,
                    nms_thresh       = WORD_NMS_THRESH,
                    zero_shot        = False,
                    dataset          = 'totaltext',
                )
            del wgen
            free_gpu()

        except torch.cuda.OutOfMemoryError:
            print("OOM")
            free_gpu()
            continue
        except Exception as e:
            print(f"err:{e}")
            continue

        if wm_np is None:
            print("none")
            continue

        words_2d = [wm_np[i, 0, :, :]
                    for i in range(wm_np.shape[0])
                    if wm_np[i, 0, :, :].sum()
                       >= line_area * WORD_MIN_AREA]

        if not words_2d:
            print("small")
            continue

        wdedup  = deduplicate_masks(words_2d)
        wlmap   = build_label_map(wdedup, lH, lW)

        wcl = []
        for lbl in range(1, len(wdedup) + 1):
            wm = (wlmap == lbl)
            if wm.sum() < 30:
                continue
            wcl.append((wm, np.where(wm)[1].mean()))
        wcl.sort(key=lambda x: x[1])

        ws = 0
        wb = Image.new('RGB', (lW, lH), (255, 255, 255))
        for w_idx, (wm, _) in enumerate(wcl, start=1):
            warr  = (wm.astype(np.uint8)) * 255
            wpath = os.path.join(
                word_dir,
                f'{line_name}W{w_idx}.png')
            if save_crop(line_pil, warr, wpath,
                         lW, lH, WORD_CROP_PAD):
                ws += 1
                total_words += 1
        print(f"→{ws}")

    unload(word_sam)
    print(f"  Words saved: {total_words}  "
          f"free={gpu_free_gb():.2f}GB")

    grand_summary.append((img_name, n_lines, total_words))
    free_gpu()

# ─────────────────────────────────────────────────────────
# SUMMARY
# ─────────────────────────────────────────────────────────
total_l = sum(r[1] for r in grand_summary)
total_w = sum(r[2] for r in grand_summary)
print(f"\n{'═'*55}")
print(f"  {'Image':<32} {'Lines':>5} {'Words':>6}")
print(f"  {'─'*45}")
for n, l, w in grand_summary:
    print(f"  {n:<32} {l:>5} {w:>6}")
print(f"  {'─'*45}")
print(f"  {'TOTAL':<32} {total_l:>5} {total_w:>6}")
print(f"{'═'*55}")
print(f"Output: {OUTPUT_ROOT}")

